import type { Product } from "./types"

export const SEED_PRODUCTS: Product[] = [
  {
    id: "bolas-de-carne",
    name: "Bolas de Carne",
    tagline: "El bocadito más pedido de Aleymi",
    description: "50 unids. albóndigas caseras en salsa especial",
    price: 15,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: "Popular",
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Nuestras bolas de carne se preparan con carne molida de primera calidad, condimentadas con especias naturales y bañadas en nuestra salsa especial de la casa.",
    howToUse: "Servir a temperatura ambiente. Ideales para reuniones y eventos. Consumir el mismo día del pedido para mayor frescura.",
    ingredients: "Carne molida de res, cebolla, ajo, huevo, pan rallado, especias naturales, sal.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "dedos-de-queso",
    name: "Dedos de Queso",
    tagline: "Crujientes por fuera, irresistibles por dentro",
    description: "50 unids. de queso o mortadela apanados",
    price: 15,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: null,
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Elaborados con queso fresco o mortadela, apanados con pan rallado artesanal y preparados al momento. Incluyen salsas para degustar.",
    howToUse: "Servir recién listos para disfrutar su textura crujiente. Acompañar con las salsas incluidas.",
    ingredients: "Queso fresco o mortadela, pan rallado, huevo, sal, aceite vegetal.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "mini-empanadillas",
    name: "Mini Empanadillas",
    tagline: "Cuatro sabores para elegir",
    description: "50 unids. sabores: queso, pollo, carne o piña",
    price: 15,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: null,
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Elaboradas con masa hojaldrada artesanal y rellenos frescos preparados el mismo día. Disponibles en cuatro sabores: queso, pollo, carne y piña. Incluyen salsas.",
    howToUse: "Servir a temperatura ambiente o calentar brevemente. Acompañar con las salsas incluidas.",
    ingredients: "Harina de trigo, mantequilla, rellenos a elección (queso/pollo/carne/piña), especias naturales.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "mini-sanduchitos",
    name: "Mini Sanduchitos",
    tagline: "El clásico perfecto para cualquier ocasión",
    description: "50 unids. queso cheddar, lechuga y jamón",
    price: 16,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: null,
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Preparados con pan tierno, queso cheddar, lechuga fresca y jamón de calidad. Cada uno armado con cuidado para una presentación impecable.",
    howToUse: "Servir frescos, idealmente el mismo día del pedido. Conservar en lugar fresco hasta el momento de servir.",
    ingredients: "Pan, queso cheddar, lechuga, jamón, mayonesa.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "mini-hamburguesas",
    name: "Mini Hamburguesas",
    tagline: "Con todos los aderezos especiales",
    description: "50 unids. con aderezos especiales",
    price: 17.50,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: "Nuevo",
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Armadas con pan artesanal, carne de res sazonada, lechuga, tomate y nuestros aderezos especiales. Uno de los favoritos de nuestros clientes.",
    howToUse: "Servir a temperatura ambiente o calentar brevemente antes de servir para mayor disfrute.",
    ingredients: "Pan de hamburguesa, carne de res, lechuga, tomate, aderezos especiales.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "mini-hotdog",
    name: "Mini Hot Dog",
    tagline: "El favorito de reuniones y fiestas",
    description: "50 unids. en pan artesanal",
    price: 17.50,
    originalPrice: null,
    image: "/images/products/miniHotdogs.png",
    badge: null,
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Preparados con pan suave artesanal, salchicha de primera calidad y aderezos clásicos. Siempre un éxito en cualquier evento.",
    howToUse: "Servir tibios para disfrutar mejor su sabor. Ideales como aperitivo o bocadito central del evento.",
    ingredients: "Pan hot dog, salchicha, mostaza, ketchup, mayonesa.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "mini-salchichas",
    name: "Mini Salchichas BBQ",
    tagline: "En nuestra irresistible salsa especial",
    description: "50 unids. en salsa BBQ especial",
    price: 10.50,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: null,
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Preparadas con salchichas de calidad y nuestra salsa BBQ casera, con un balance perfecto entre dulce y ahumado.",
    howToUse: "Servir calientes para mejor sabor. Presentar con palillos para facilitar el servicio.",
    ingredients: "Mini salchichas, salsa BBQ casera (tomate, azúcar morena, vinagre, especias).",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "tartaletas",
    name: "Tartaletas",
    tagline: "El toque gourmet del menú Aleymi",
    description: "50 unids. de pollo o camarón",
    price: 18.50,
    originalPrice: null,
    image: "/images/products/producto1.png",
    badge: "Popular",
    category: "bocaditos",
    sizes: ["50 unidades"],
    details: "Elaboradas con masa quebrada artesanal y rellenas de pollo o camarón con queso crema, decoradas para una presentación impecable.",
    howToUse: "Servir a temperatura ambiente. Consumir el mismo día para mantener la textura crujiente de la masa.",
    ingredients: "Masa quebrada, pollo o camarón, queso crema, especias, perejil.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "bandeja-completa",
    name: "Bandeja Completa",
    tagline: "Para llenar tu evento de sabor",
    description: "100 piqueos surtidos seleccionados",
    price: 29,
    originalPrice: null,
    image: "/images/products/bandejaClasica.png",
    badge: "Nuevo",
    category: "bandejas",
    sizes: ["100 piqueos surtidos"],
    details: "Incluye una selección de 100 bocaditos variados del menú Aleymi, presentados en bandeja con salsas para degustar incluidas.",
    howToUse: "Servir a temperatura ambiente. Ideal para eventos de 15-20 personas. Incluye salsas.",
    ingredients: "Selección surtida de bocaditos del menú Aleymi.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
  {
    id: "bandeja-personalizada",
    name: "Bandeja Personalizada",
    tagline: "Tu elección, nuestro sabor",
    description: "Piqueos a tu elección — desde $2.75 c/u",
    price: 2.75,
    originalPrice: null,
    image: "/images/products/bandejaClasica.png",
    badge: null,
    category: "bandejas",
    sizes: ["Mínimo 50 unidades"],
    details: "Puedes combinar libremente todos los bocaditos del menú. Mézclanos como quieras — precio por unidad desde $2.75.",
    howToUse: "Consultar disponibilidad y combinar con los bocaditos de tu preferencia. Servir a temperatura ambiente.",
    ingredients: "Selección a elección del menú Aleymi.",
    delivery: "Pedidos con 2 días de anticipación y previo abono. Consultar disponibilidad para su fecha.",
  },
]
